apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: 'localhost'
  namespace: 'gloo-system'
spec:
  virtualHost:
    domains:
      - 'localhost'
    routes:
      - matchers:
          - prefix: '/' # delegate ownership of all routes for `localhost`
        delegateAction:
          selector:
            labels:
              domain: localhost
            namespaces:
              - gloo-system
